### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by yrane** [atom-community/autocomplete-snippets#32]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.18.3-201.fc21.x86_64
**Thrown From**: [autocomplete-snippets](https://github.com/atom-community/autocomplete-snippets) package, v1.0.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/local/share/atom/resources/app/src/scope-descriptor.js:29

TypeError: undefined is not a function
  at ScopeDescriptor.module.exports.ScopeDescriptor.getScopeChain (/usr/local/share/atom/resources/app/src/scope-descriptor.js:29:26)
  at Config.module.exports.Config.getRawScopedValue (/usr/local/share/atom/resources/app/src/config.js:733:72)
  at Config.module.exports.Config.get (/usr/local/share/atom/resources/app/src/config.js:164:22)
  at SnippetsProvider.module.exports.SnippetsProvider.requestHandler (/home/yrane/.atom/packages/autocomplete-snippets/lib/snippets-provider.coffee:11:33)
  at /home/yrane/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:115:39
  at Array.map (native)
  at AutocompleteManager.module.exports.AutocompleteManager.scatterRequest (/home/yrane/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:114:27)
  at AutocompleteManager.scatterRequest (/home/yrane/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.runAutocompletion (/home/yrane/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:109:6)
  at /home/yrane/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

```

### Commands

```
     -0:38.3 editor:newline (input.hidden-input)
     -0:00.0 settings-view:open (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.0.6
autocomplete-snippets, v1.0.0
linter, v0.10.1
minimap, v3.5.6
monokai, v0.12.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by joefitzgerald** [comment]
Could you try again with the latest version of autocomplete-plus?

**Comment by yrane** [comment]
I just update autocomplete-plus to v2.1.0 and still getting the error.

1. Start typing some java code

**Atom Version**: 0.165.0
**System**: linux 3.18.3-201.fc21.x86_64
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.1.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/yrane/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:167

TypeError: undefined is not a function
  at FuzzyProvider.module.exports.FuzzyProvider.settingsForScopeDescriptor (/home/yrane/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:167:27)
  at FuzzyProvider.module.exports.FuzzyProvider.getCompletionsForCursorScope (/home/yrane/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:175:20)
  at FuzzyProvider.getCompletionsForCursorScope (/home/yrane/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:1:1)
  at FuzzyProvider.module.exports.FuzzyProvider.findSuggestionsForWord (/home/yrane/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:152:34)
  at FuzzyProvider.findSuggestionsForWord (/home/yrane/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:1:1)
  at FuzzyProvider.module.exports.FuzzyProvider.requestHandler (/home/yrane/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:63:20)
  at FuzzyProvider.requestHandler (/home/yrane/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:1:1)
  at /home/yrane/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:116:63
  at Array.map (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/home/yrane/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:116:35)
  at AutocompleteManager.getSuggestionsFromProviders (/home/yrane/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/home/yrane/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:112:6)
  at /home/yrane/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

```

### Commands

```
     -6:18.9 settings-view:open (input.hidden-input)
  3x -5:57.7 core:move-up (input.hidden-input)
  3x -5:56.9 core:move-right (input.hidden-input)
     -5:55.5 core:move-up (input.hidden-input)
  4x -5:55.1 core:move-right (input.hidden-input)
  3x -5:54.0 core:move-up (input.hidden-input)
     -0:02.0 core:move-down (input.hidden-input)
     -0:00.5 snippets:next-tab-stop (input.hidden-input)
     -0:00.5 snippets:expand (input.hidden-input)
     -0:00.4 editor:indent (input.hidden-input)
  2x -0:00.0 editor:newline (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "bone-a-kite"
    ]
  },
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.0
autocomplete-snippets, v1.0.1
bone-a-kite, v1.0.0
linter, v0.10.1
minimap, v3.5.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by joefitzgerald** [comment]
You haven't updated **atom** itself: 

> Atom Version: 0.165.0

The latest version is `0.177.0`.
